### ISSUE TITLE
MyPal and Youtube

### ISSUE THREAD

**Issue by tptlja** [Feodor2/Mypal#132]
"We will soon stop supporting this browser. To enjoy all the benefits of YouTube, install another One."

What should we do now?

**Comment by rocky7717** [comment]
There is a NEW version of Palemoon 28.8.2.1 out that will address this problem....

**Comment by ByRodrigoSoares** [comment]
JUST CHANGE THE User Agent String

**Comment by ByRodrigoSoares** [comment]
About:config
general.useragent.override.gaming.youtube.com
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0

just change the string to the ones below

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:64.0) Gecko/20100101 Firefox/64.0

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:62.0) Gecko/20100101 Firefox/64.0 PaleMoon/28.8.1

**Comment by joeturnes** [comment]
> 
> 
> "We will soon stop supporting this browser. To enjoy all the benefits of YouTube, install another One."
> 
> What should we do now?

Oddly, you do NOT get that warning with ancient last vers for XP Firefox 52.9.0 esr.
When i 1st saw that youtube warning in MyPal(& sister browser, New moon) i really thought i was in BIG trouble, & it was time to throw out my XP desktop & get a windows 10 one. 
But would my visual pinball tables, doom II, & original 2007 magicjack still work on windows 10? lol

**Comment by ByRodrigoSoares** [comment]
> 
> 
> There is a NEW version of Palemoon 28.8.2.1 out that will address this problem....

**Yes, it has already been resolved in Palemoon. I hope it will also be resolved in MyPal.**

**Comment by ByRodrigoSoares** [comment]
1°About:config

2°Type in the bar to search for the key and change it

general.useragent.override.gaming.youtube.com

3°change the string of your two keys

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:62.0) Gecko/20100101 Firefox/62.0

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:62.0) Gecko/20100101 Firefox/62.0 PaleMoon/28.8.1

**Comment by ByRodrigoSoares** [comment]
> 
> 
### > 1°About:config
> 
> 2°Type in the bar to search for the key and change it
> 
> general.useragent.override.gaming.youtube.com
> 
> 3°change the string of your two keys
> 
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:62.0) Gecko/20100101 Firefox/62.0
> 
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:62.0) Gecko/20100101 Firefox/62.0 PaleMoon/28.8.1

I took the test and it works I hope I helped

**Comment by ByRodrigoSoares** [comment]
**I took the test and it works I hope I helped**

**Comment by hue4** [comment]
> 
> 
> 1°About:config
> 
> 2°Type in the bar to search for the key and change it
> 
> general.useragent.override.gaming.youtube.com
> 
> 3°change the string of your two keys
> 
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:62.0) Gecko/20100101 Firefox/62.0
> 
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:62.0) Gecko/20100101 Firefox/62.0 PaleMoon/28.8.1

Tried but so far still getting the youtube message.  Maybe there's a step I'm missing?

**Comment by ewuc** [comment]
I'm using the following on MyPal 28.8.1 and it works fine(on Windows XP):
**About:config**  add new string:
**name**
general.useragent.override.youtube.com
**value**
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 PaleMoon/28.8.1

**Comment by krystian3w** [comment]
Workaround with only UA may no enough if Material Design version has updated on 1/31 March 2020.

**Comment by krystian3w** [comment]
Workaround with only UA may no enough if Material Design version has updated on 1/31 March 2020.

**Comment by caloberg** [comment]
hi ,  using a dell inspirion 8600 laptop running windows xp sp3
just installed MyPal v.28.8.4 ,32bit
YouTube seems to function, when playing a video, it does not display any video, only the audio.

**Comment by krystian3w** [comment]
> `general.useragent.override.gaming.youtube.com`

gaming subdomain disabled in 2019...
